// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLMA.Models;

#nullable disable

namespace QLMA.Migrations
{
    [DbContext(typeof(QLMAContext))]
    [Migration("20250322191154_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLMA.Models.ADMIN", b =>
                {
                    b.Property<int>("ID_AD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_AD"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_AD");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("QLMA.Models.BaoCaoThongKe", b =>
                {
                    b.Property<int>("ID_BaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_BaoCao"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiBaoCao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenBaoCao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_BaoCao");

                    b.ToTable("BaoCaoThongKes");
                });

            modelBuilder.Entity("QLMA.Models.DiemPhatThucPham", b =>
                {
                    b.Property<int>("ID_DPTT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_DPTT"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_ToChucTuThien")
                        .HasColumnType("int");

                    b.Property<string>("TenDiem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_DPTT");

                    b.ToTable("DiemPhatThucPhams");
                });

            modelBuilder.Entity("QLMA.Models.NguoiCanHoTro", b =>
                {
                    b.Property<int>("ID_NCHT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_NCHT"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_NCHT");

                    b.ToTable("NguoiCanHoTros");
                });

            modelBuilder.Entity("QLMA.Models.NhaHaoTam", b =>
                {
                    b.Property<int>("ID_NHT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_NHT"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_NHT");

                    b.ToTable("NhaHaoTams");
                });

            modelBuilder.Entity("QLMA.Models.NhaTuyenDung", b =>
                {
                    b.Property<int>("ID_NTD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_NTD"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenCongTy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_NTD");

                    b.ToTable("NhaTuyenDungs");
                });

            modelBuilder.Entity("QLMA.Models.NoiO", b =>
                {
                    b.Property<int>("ID_NoiO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_NoiO"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lienhe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sogiuongcosan")
                        .HasColumnType("int");

                    b.Property<string>("TenNoiO")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_NoiO");

                    b.ToTable("NoiOs");
                });

            modelBuilder.Entity("QLMA.Models.PDKVL", b =>
                {
                    b.Property<int>("ID_PDKVL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_PDKVL"));

                    b.Property<int>("ID_NguoiDangKy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayUngTuyen")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDangKyID_NCHT")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_PDKVL");

                    b.HasIndex("NguoiDangKyID_NCHT");

                    b.ToTable("PhieuDKVLs");
                });

            modelBuilder.Entity("QLMA.Models.PhieuDangKy", b =>
                {
                    b.Property<int>("ID_PDK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_PDK"));

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_NguoiDangKy")
                        .HasColumnType("int");

                    b.Property<int>("ID_NoiO")
                        .HasColumnType("int");

                    b.Property<string>("LoaiDangKy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDangKy")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_PDK");

                    b.ToTable("PhieuDangKies");
                });

            modelBuilder.Entity("QLMA.Models.QLDPTP", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_DPTT")
                        .HasColumnType("int");

                    b.Property<int>("ID_TCTT")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_DPTT");

                    b.HasIndex("ID_TCTT");

                    b.ToTable("QLDPTTs");
                });

            modelBuilder.Entity("QLMA.Models.QuanLy", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Admin")
                        .HasColumnType("int");

                    b.Property<int>("ID_Bang")
                        .HasColumnType("int");

                    b.Property<string>("LoaiHanhDong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayThucHien")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenBang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ID_Admin");

                    b.ToTable("QuanLys");
                });

            modelBuilder.Entity("QLMA.Models.QuyenGop", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ID_NhaHaoTam")
                        .HasColumnType("int");

                    b.Property<int>("ID_ToChucTuThien")
                        .HasColumnType("int");

                    b.Property<string>("LoaiQG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGop")
                        .HasColumnType("datetime2");

                    b.Property<float>("Soluong")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("QuyenGops");
                });

            modelBuilder.Entity("QLMA.Models.TinhNguyenVien", b =>
                {
                    b.Property<int>("ID_TNV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_TNV"));

                    b.Property<string>("CCCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_ToChucTuThien")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_TNV");

                    b.HasIndex("ID_ToChucTuThien");

                    b.ToTable("TinhNguyenViens");
                });

            modelBuilder.Entity("QLMA.Models.ToChucTuThien", b =>
                {
                    b.Property<int>("ID_TCTT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_TCTT"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loaihinhhotro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenToChuc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_TCTT");

                    b.ToTable("ToChucTuThiens");
                });

            modelBuilder.Entity("QLMA.Models.ViecLam", b =>
                {
                    b.Property<int>("ID_VL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_VL"));

                    b.Property<int>("ID_NhaTuyenDung")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MucLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenViec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yeucaukynang")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_VL");

                    b.HasIndex("ID_NhaTuyenDung");

                    b.ToTable("ViecLams");
                });

            modelBuilder.Entity("QLMA.Models.PDKVL", b =>
                {
                    b.HasOne("QLMA.Models.NguoiCanHoTro", "NguoiDangKy")
                        .WithMany()
                        .HasForeignKey("NguoiDangKyID_NCHT");

                    b.Navigation("NguoiDangKy");
                });

            modelBuilder.Entity("QLMA.Models.QLDPTP", b =>
                {
                    b.HasOne("QLMA.Models.DiemPhatThucPham", "DiemPhatThucPham")
                        .WithMany()
                        .HasForeignKey("ID_DPTT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLMA.Models.ToChucTuThien", "ToChucTuThien")
                        .WithMany()
                        .HasForeignKey("ID_TCTT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiemPhatThucPham");

                    b.Navigation("ToChucTuThien");
                });

            modelBuilder.Entity("QLMA.Models.QuanLy", b =>
                {
                    b.HasOne("QLMA.Models.ADMIN", "Admin")
                        .WithMany()
                        .HasForeignKey("ID_Admin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("QLMA.Models.TinhNguyenVien", b =>
                {
                    b.HasOne("QLMA.Models.ToChucTuThien", "ToChucTuThien")
                        .WithMany()
                        .HasForeignKey("ID_ToChucTuThien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToChucTuThien");
                });

            modelBuilder.Entity("QLMA.Models.ViecLam", b =>
                {
                    b.HasOne("QLMA.Models.NhaTuyenDung", "NhaTuyenDung")
                        .WithMany()
                        .HasForeignKey("ID_NhaTuyenDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaTuyenDung");
                });
#pragma warning restore 612, 618
        }
    }
}
